#!/bin/bash

echo "폴더 이름을 입력하세요: "
read folder_name

if [ ! -d "$folder_name" ]; then
  mkdir "$folder_name"
  echo "폴더가 생성되었습니다."
else
  echo "폴더가 이미 존재합니다."
fi

cd "$folder_name"

for ((i = 1; i <= 5; i++)); do
  touch "file$i.txt"
  echo "file$i.txt 생성됨"
done

zip -r "$folder_name.zip" ./*

mkdir "unzipped_folder"
unzip "$folder_name.zip" -d "unzipped_folder"

echo "압축 해제 완료"
