#!/bin/bash

echo "리눅스가 재미있나요? (yes / no)"
read answer

case $answer in
    yes)
        echo "y"
        ;;
    y)
        echo "y"
        ;;
    no)
        echo "no"
        ;;
    nonono)
        echo "no"
        ;;
    *)
echo "잘못된 입력입니다."
        ;;

esac
